name: Release


on:
  release:
    types: [published]
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            jordywalraven/ciri2-fe:latest
            jordywalraven/ciri2-fe:${{ github.sha }}

  lighthouse:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and run Docker image
        run: |
          docker pull jordywalraven/ciri2-fe:latest
          docker run -d -p 80:80 jordywalraven/ciri2-fe:latest

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            http://localhost:80
          uploadArtifacts: true
          configPath: ./lighthouserc.json # custom lighthouse configuration
          temporaryPublicStorage: true



